# Generated by nitcc for the language butter

# Standalone parser tester for the language butter
module butter_test_parser
import nitcc_runtime
import butter_lexer
import butter_parser

# Class to test the parser for the language butter
class TestParser_butter
	super TestParser
	redef fun name do return "butter"
	redef fun new_lexer(text) do return new Lexer_butter(text)
	redef fun new_parser do return new Parser_butter
end
var t = new TestParser_butter
t.main
